export interface Booking {
  id?: string; // Optional, as it might be generated by the backend on creation
  userId: string; // The ID of the user making the booking (from AuthService)
  tailorId: string; // The ID of the tailor being booked
  bookingDate: string; // e.g., 'YYYY-MM-DD' - Date of the service
  deliveryDate: string; // e.g., 'YYYY-MM-DD' - New: Expected delivery date
  serviceType: string; // e.g., 'Custom Suit', 'Alterations', 'Dressmaking'
  fixedCost: number; // New: Fixed cost for the service
  clothHandlingOption: 'Delivering Myself' | 'Buy by Tailor' | 'Get from Supplier'; // New: How cloth is handled
  description: string; // New: Detailed description of the booking/requirements (renamed from 'notes')
  status?: 'Pending' | 'Confirmed' | 'Completed' | 'Cancelled'; // Status, set by backend
  createdAt?: string; // Timestamp, generated by backend
  // Add any other relevant booking details
}